#pragma once

// #define LOG_SKILL_FROM_BUILD

#ifndef _DEBUG
#ifdef LOG_SKILL_FROM_BUILD
#undef LOG_SKILL_FROM_BUILD
#endif
#endif

#define USE_ANY_SKILL_FROM_BUILD_LOGIC
#define USE_SKILL_ID_AND_NAME_MATCH_LOGIC
#define USE_TIME_FILTER_LOGIC

#ifndef USE_SKILL_ID_AND_NAME_MATCH_LOGIC
#define USE_SKILL_ID_MATCH_LOGIC
#endif

#define USE_SKIP_NEXT_SKILL
#define USE_SKIP_NEXT_NEXT_SKILL
#define USE_SKIP_NEXT_NEXT_NEXT_SKILL

// #define USE_ADVANCED_SKILL_DETECTION_LOGIC
