#ifndef VERSION_H
#define VERSION_H

#define MAJOR 3
#define MINOR 3
#define BUILD 0
#define REVISION 0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define VERSION_STRING TOSTRING(MAJOR) "." TOSTRING(MINOR) "." TOSTRING(BUILD) "." TOSTRING(REVISION)

#define LOWER_VERSION_RANGE "3.0.0.0"
#define UPPER_VERSION_RANGE "3.3.0.0"

#define BUILD_DATE "2026-02-19"
#define BUILD_STR std::string{BUILD_DATE}

#endif // VERSION_H
